name: build-test
on: [pull_request, push]

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.16"

      - name: check fmt
        run: |
          make fmt-check

      - name: vet
        run: |
          make vet

      - name: test
        run: |
          make test

      - name: build
        run: |
          make
